# Generated by Django 4.0 on 2021-12-20 18:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], help_text='Which answer is correct: 1, 2, 3 or 4?', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('slug', models.SlugField(db_column='Category_url', help_text='Category_url', unique=True)),
                ('color', models.CharField(default='#', max_length=10)),
                ('description', models.TextField(default='Category description', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('points', models.PositiveIntegerField(default=1, help_text='1 - 3 points', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('approved', models.BooleanField(default=True, help_text='Does the question meet the rules and can be added to one of the quizzes?')),
                ('answers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.answer')),
                ('category', models.ForeignKey(blank=True, db_column='category_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Quiz description', max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='quiz.category', to_field='name')),
                ('question', models.ManyToManyField(to='quiz.Question')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
